config/routes.rb
Rails.application.routes.draw do
 
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  
 
  namespace :admin do
    root to: "homes#top"
    resources :order_details,only: [:update]
    resources :orders,only: [:update, :show]
    resources :customers,only: [:index, :update, :show, :create, :edit]
    resources :items,only: [:index, :new, :show, :update, :create, :edit]
  end
 
  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources :deliveries,only: [:index, :edit, :create, :update, :destroy]
    resources :orders,only: [:index, :show, :new, :create] do
      collection do
        post :confirm
        get :complete
      end 
    end  
    resources :items,only: [:index, :show]
    resources :cart_items,only: [:index, :update, :destroy, :create] do
      collection do
        delete :destroy_all   
      end
    end
    resources :customers, only: [:edit, :update, :show] do
      collection do
        patch :secession
        get :complete
      end 
    end
    
    
    get "/customers/information/edit" => "public/customers#edit"
    get "/customers/mypage" => "public/customers#show"
   
  
  end
  
  
  
  
 



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  has_one_attached :image
  
  
def subtotal
    item.with_tax_price * amount
end
 
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
        
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer
  
  def delivery_display
  '〒' + gip_code + ' ' + address + ' ' + address_name
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :itemcarts, dependent: :destroy
  has_many :orderdetails, dependent: :destroy
  has_one_attached :image
  
  def with_tax_price
    (price * 1.1).floor
  end
  
end

app/models/itemcart.rb
class Itemcart < ApplicationRecord
  belongs_to :customer
  belongs_to :cart_item
  
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_methods: { credit_card: 0, transfer: 1 }
 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :item
  belongs_to :order
end

app/models/orderdetail.rb
class Orderdetail < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :item
  belongs_to :order
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to  admin_customers_path
  end
  
  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :is_delete)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    #@orders = orders.customer
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  
  
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to  admin_item_path
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
   private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active)
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
  end
  
  private

  def order_params
    params.require(:order).permit(:address, :gip_code, :address_name, :payment_methods, :invoice_amount, :postage, :order_status)
  end
  
  
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    admin_root_path
  end
  
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
   #before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:telephone_number])
    
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/item_helper.rb
module Admin::ItemHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
   <p id ="notice"></p>
   
     <div class="col w-50 text-dark bg-light text-center mb-4 ml-5"><h4><%= @customer.first_name %><% @customer.last_name %>さんの会員情報</h4></div>
   
  
   <div class="row">
    <%= form_with model: @customer, url: admin_customer_path(params[:id]) do |f| %>
    
    <div class="field">
    <div class="row ">
      <div class="col-sm-4">
      <%= f.label "氏名", class: "col-form-label" %>
      </div>
      
      <div class="col-sm-1"></div>
      <div class="col-sm-3">
      <%= f.text_field :first_name, class:"form-control-sm" %>
      </div>

      <div class="col-sm-3">
      <%= f.text_field :last_name, class: 'form-control-sm ' %>
      </div>
    </div>
  </div>
      
      
  <div class="field">
    <div class="row">
      <div class="col-sm-4">
      <%= f.label "フリガナ", class: "col-form-label" %>
      </div>
      
      <div class="col-sm-1"></div>
      <div class="col-sm-3">
      <%= f.text_field :first_name_kana, class: 'form-control-sm ' %>
      </div>
      
      <div class="col-sm-3">
      <%= f.text_field :last_name_kana, class: 'form-control-sm ' %>
      </div>
    </div>
  </div>
    
  <div class="field">
    <div class="row">
      <div class="col-sm-4">
      <%= f.label "郵便番号", class: "col-form-label" %>
      </div>
      <div class="col-sm-1"></div>
      <div class="col-sm-3">
      <%= f.text_field :postal_code, class: 'form-control-sm ' %>
      </div>
    </div>
  </div>
  
  <div class="field">
    <div class="row">
      <div class="col-sm-4">
      <%= f.label "住所", class: "col-form-label" %>
      </div>
      <div class="col-sm-1"></div>
      <div class="col-sm-3">
      <%= f.text_field :address, class: 'form-control-sm ' %>
      </div>
    </div>
  </div>
     
  <div class="field">
    <div class="row">
      <div class="col-sm-4">
      <%= f.label "電話番号", class: "col-form-label" %>
      </div>
      <div class="col-sm-1"></div>
      <div class="col-sm-3">
      <%= f.text_field :telephone_number, class: 'form-control-sm ' %>
      </div>
    </div>
  </div>
  
   <div class="field">
    <div class="row">
      <div class="col-sm-4">
      <%= f.label "メールアドレス" , class: "col-form-label" %>
      </div>
      <div class="col-sm-1"></div>
      <div class="col-sm-3">
      <%= f.text_field :email,autofocus: true, autocomplete: "email", class: 'form-control-sm ' %>
      </div>
    </div>
  </div>
  
   <div class="field">
    <div class="row">
      <div class="col-sm-4">
      <%= f.label "会員ステータス" , class: "col-form-label" %>
      </div>
      <div class="col-sm-1"></div>
      <div class="col-sm-3">
      <div class="form-check">
        <%= f.radio_button :is_active, true, class: "form-check-input" %>
        <%= f.label :is_active, "有効", value: true, class: "form-check-label" %>
      </div>
      <div class="form-check">
        <%= f.radio_button :is_active, false, class: "form-check-input" %>
        <%= f.label :is_active, "退会", value: false, class: "form-check-label" %>
    </div>
      </div>
    </div>
  </div>
    
    
    
    
    <div class="actions text-center col-6 col-sm-4 py-2">
      <%= f.submit "変更を保存", class:"btn btn-success" %>
    </div>
  <% end %>
   
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <p id ="notice"></p>
    <h4 class="text-dark bg-light w-25 text-center mb-y">会員一覧</h4>
    
    
    <table class="table">
      <thead>
        <tr>
          <th scope="col">会員ID</th>
          <th scope="col">氏名</th>
          <th scope="col">メールアドレス</th>
          <th scope="col">ステータス</th>
        </tr>
      </thead>
      
      
      
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to  admin_customer_path(customer.id)  do %>
            <%= customer.first_name %><%= customer.last_name %>
            <% end %>
          </td>
          <td><%= customer.email  %></td>
          <td><% if customer.is_deleted == false %>
              有効
              <% else %>
              退会
              <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
      
    </table>
    
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <p id ="notice"></p>
  
  <div class="col w-50 text-dark bg-light text-center mb-4 ml-5"><h4><%= @customer.first_name %><% @customer.last_name %>さんの会員情報</h4></div>
   
  
  <div class="row">
    
    <div class="col-6 col-sm-4 bg-light border py-2">会員ID</div>
    <div class="col-6 col-sm-6 border py-2"><%= @customer.id %></div>
    
    <div class="col-6 col-sm-4 bg-light border py-2">氏名</div>
    <div class="col-6 col-sm-6 border py-2"><%= @customer.first_name %>
    <%= @customer.last_name %></div>
    
    <div class="w-100"></div>
    <div class="col-6 col-sm-4 bg-light border py-2">カナ</div>
    <div class="col-6 col-sm-6 border py-2"><%= @customer.first_name_kana %>
    <%= @customer.last_name_kana %></div>
    
    <div class="w-100"></div>
    <div class="col-6 col-sm-4 bg-light border py-2">郵便番号</div>
    <div class="col-6 col-sm-6 border py-2"><%= @customer.postal_code %></div>
    
    <div class="w-100"></div>
    <div class="col-6 col-sm-4 bg-light border py-2">住所</div>
    <div class="col-6 col-sm-6 border py-2"><%= @customer.address %></div>
    
    <div class="w-100"></div>
    <div class="col-6 col-sm-4 bg-light border py-2">電話番号</div>
    <div class="col-6 col-sm-6 border py-2"><%= @customer.telephone_number %></div>
    
    <div class="w-100"></div>
    <div class="col-6 col-sm-4 bg-light border py-2">メールアドレス</div>
    <div class="col-6 col-sm-6 border py-2"><%= @customer.email %></div>
  
    <div class="w-100"></div>
    <div class="col-6 col-sm-4 bg-light border py-2">会員ステータス</div>
    <div class="col-6 col-sm-6 border py-2">
      <% if @customer.is_deleted == false %>
        有効
      <% else %>
        退会
      <% end %>
    </div>
  
  
  </div>
    
  <div class="row my-3">
    <div class="row">
      <div class="col-sm-1"></div>
      <%= link_to "編集する", edit_admin_customer_path(params[:id]), class: "btn btn-success" %>
    </div>
  </div>
    
  <div class="row my-3">
    <div class="row">
      <div class="col-sm-1"></div>
      <%= link_to "注文履歴一覧を見る", admin_order_path(params[:id]), class: "btn btn-primary" %>
    </div>
  </div>
    
 
</div>

app/views/admin/items/edit.html.erb
<div class="container">
   <p id ="notice"></p>
   
   <div class="col-sm-2 text-dark bg-light text-center mb-4 ml-5">
     <h4>商品編集</h4>
   </div>
   
  <%= form_with model: @item, url: admin_item_path do |f| %>
   <div class="row">
    
    
    <div class="col-6 col-sm-4 py-2">商品画像</div>
    <div class="col-6 col-sm-6 py-2"><%= f.file_field :image, accept: "image/*" %></div>
    
    <div class="col-6 col-sm-4 py-2">商品名</div>
    <div class="col-6 col-sm-6 py-2"> <%= f.text_field :name, class: 'form-control-sm '%></div>
    
    <div class="w-75"></div>
    <div class="col-6 col-sm-4 py-2">商品説明</div>
    <div class="col-6 col-sm-6 py-2"><%= f.text_area :introduction, class: 'form-control-sm ' %></div>
    
    <div class="w-75"></div>
    <div class="col-6 col-sm-4 py-2">税抜価格</div>
    <div class="col-6 col-sm-6 py-2"> <%= f.text_area :price, class: 'form-control-sm ' %>円</div>
  
    <div class="w-75"></div>
    <div class="col-6 col-sm-4 py-2">販売ステータス</div>
    
    <div class="form-check">
      <%= f.radio_button :is_active, true, class: "form-check-input" %>
      <%= f.label :is_active, "販売中", value: true, class: "form-check-label" %>
    </div>

    <div class="form-check">
      <%= f.radio_button :is_active, false, class: "form-check-input" %>
      <%= f.label :is_active, "販売停止中", value: false, class: "form-check-label" %>
    </div>
    
     <div class="actions text-center">
      <%= f.submit "変更を保存", class:"btn btn-success" %>
    </div>
  <% end %>
   
</div>

app/views/admin/items/index.html.erb
    
    
<div class="container">
  <p id ="notice"></p>
  
  <div class="row">
    <div class="text-dark bg-light w-25 text-center mb-y col-sm-2"><h4>商品一覧</h4></div>
    <div class="col-sm-8"></div>
    <div class="col-sm-2"><%= link_to "+",  new_admin_item_path %></div>
  </div>
  
    <table class="table mt-4">
      <thead>
        <tr>
          <th scope="col">商品ID</th>
          <th scope="col">商品名</th>
          <th scope="col">税抜価格</th>
          <th scope="col">ステータス</th>
        </tr>
      </thead>
      
      
      
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to admin_item_path(item.id) do %>
              <%= item.name %>
              <% end %></td>
          <td><%= item.price  %></td>
          <td><% if item.is_active == true %>
                販売中
              <% else %>
                販売停止中
              <% end %></td>
        </tr>
        <% end %>
      </tbody>
      
    </table>
    
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <p id ="notice"></p>
    <h5 class="text-dark bg-light text-left w-25 mb-4 px-3">商品新規登録</h5>
    
    <%= form_with model: @item, url: "/admin/items", method: :post do |f| %>
    
    <div class="field">
      <div class="row">
        <div class="col">
          <%= f.label "商品画像" , class: "col-sm-3 col-form-label" %>
          <%= f.file_field :image, accept: "image/*" %>
        </div>
      </div>
    </div>
    
    <div class="field">
      <div class="row">
        <div class="col">
          <%= f.label "商品名" , class: "col-sm-3 col-form-label" %>
          <%= f.text_field :name, class: 'form-control-sm '%>
        </div>
      </div>
    </div>
    
    <div class="field">
      <div class="row">
        <div class="col">
          <div class="md-3">
          <%= f.label "商品説明" , class: "col-sm-3 col-form-label" %>
          <%= f.text_area :introduction, class: 'form-control-sm ' %>
          </div>
        </div>
      </div>
    </div>
    
    <div class="field">
      <div class="row">
        <div class="col">
          <%= f.label "税抜価格" , class: "col-sm-3 col-form-label" %>
          <%= f.text_area :price,class: 'form-control-sm ' %>円
        </div>
      </div>
    </div>
    
    <div class="field">
      <div class="row">
        <div class="col">
          <%= f.label "販売ステータス" , class: "col-sm-3 col-form-label" %>
          <div class="form-check">
            <input class="form-check-input" type="radio">
              <label class="form-check-label" for="flexRadioDefault1">
                販売中
              </label>
          </div>
          
          <div class="form-check">
            <input class="form-check-input" type="radio">
              <label class="form-check-label" for="flexRadioDefault2">
                販売停止中
              </label>
          </div>
        </div>
      </div>
    </div>
    
    
        
    <div class="actions text-center">
      <%= f.submit "新規登録" %>
    </div>
          
    <% end %>
    
    
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <p id ="notice"></p>
  
  <div class="col-sm-2 text-dark bg-light text-center mb-4 ml-5"><h4>商品詳細</h4></div>
  
   <div class="row">
     
    <div class="col-6 col-sm-6 py-2"><%= image_tag @item.image, size: '300x200' %></div>
    
   
    <div class="w-75"></div>
    <div class="col-6 col-sm-4 py-2">商品名</div>
    <div class="col-6 col-sm-6 py-2"><%= @item.name %></div>
    
    <div class="w-75"></div>
    <div class="col-6 col-sm-4 py-2">商品説明</div>
    <div class="col-6 col-sm-6 py-2"><%= @item.introduction %></div>
    
    <div class="w-75"></div>
    <div class="col-6 col-sm-4 py-2">税込価格(税抜価格)</div>
    <div class="col-6 col-sm-6 py-2"><%= (@item.price*1.10).floor %>
    (<%= @item.price %>)円</div>
  
    <div class="w-75"></div>
    <div class="col-6 col-sm-4 py-2">販売ステータス</div>
    <div class="col-6 col-sm-6 py-2"><% if @item.is_active == true %>
                                     販売中
                                     <% else %>
                                     販売停止中
                                     <% end %>
  
    <div class="actions text-center">
      <%= link_to  "編集する",  edit_admin_item_path(@item[:id]), class:"btn btn-success"  %>
    </div>
  
  </div>
    
  
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <p id ="notice"></p>
  
  <div class="col-sm-3 text-dark bg-light text-center mb-4 ml-5"><h4>注文履歴詳細</h4></div>
  
   <div class="row">
     
    <div class="col-6 col-sm-4 py-2">購入者</div>
    <div class="col-6 col-sm-6 py-2"><%= @order.address_name %></div>
    
    <div class="w-75"></div>
    <div class="col-6 col-sm-4 py-2">注文日</div>
    <div class="col-6 col-sm-6 py-2"><%= @order.created_at%></div>
    
    <div class="w-75"></div>
    <div class="col-6 col-sm-4 py-2">配送先</div>
    <div class="col-6 col-sm-6 py-2"><%= @order.address %></div>
  
    <div class="w-75"></div>
    <div class="col-6 col-sm-4 py-2">支払方法</div>
    <div class="col-6 col-sm-6 py-2">
        <% if @order.payment_methods == 0 %>
         クレジットカード
        <% else %>
         銀行振込
        <% end %>
    </div>
  
    <div class="w-75"></div>
    <div class="col-6 col-sm-4 py-2">商品合計</div>
    <div class="col-6 col-sm-6 py-2"><%= @order.invoice_amount %> 円</div>
    
    <div class="w-75"></div>
    <div class="col-6 col-sm-4 py-2">送料</div>
    <div class="col-6 col-sm-6 py-2"><%= @order.postage %> 円</div>
    
    <div class="w-75"></div>
    <div class="col-6 col-sm-4 py-2">請求金額合計</div>
    <div class="col-6 col-sm-6 py-2"><%= @order.invoice_amount + (@order.postage) %> 円</div>
    
 
  
        </div>
    </div>  
    
  
  
  </div>
    
  
</div>