config/routes.rb
Rails.application.routes.draw do
 
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  
 
  namespace :admin do
    root to: "homes#top"
    resources :order_details,only: [:update]
    resources :orders,only: [:update, :show]
    resources :customers,only: [:index, :update, :show, :create, :edit]
    resources :items,only: [:index, :new, :show, :update, :create, :edit]
  end
 
  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources :deliveries,only: [:index, :edit, :create, :update, :destroy]
    resources :orders,only: [:index, :show, :new, :create] do
      collection do
        post :confirm
        get :complete
      end 
    end  
    resources :items,only: [:index, :show]
    resources :cart_items,only: [:index, :update, :destroy, :create] do
      collection do
        delete :destroy_all   
      end
    end
    resources :customers, only: [:edit, :update, :show] do
      collection do
        patch :secession
        get :complete
      end 
    end
    
    
    get "/customers/information/edit" => "public/customers#edit"
    get "/customers/mypage" => "public/customers#show"
   
  
  end
  
  
  
  
 



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  has_one_attached :image
  
  
def subtotal
    item.with_tax_price * amount
end
 
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
        
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer
  
  def delivery_display
  '〒' + gip_code + ' ' + address + ' ' + address_name
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :itemcarts, dependent: :destroy
  has_many :orderdetails, dependent: :destroy
  has_one_attached :image
  
  def with_tax_price
    (price * 1.1).floor
  end
  
end

app/models/itemcart.rb
class Itemcart < ApplicationRecord
  belongs_to :customer
  belongs_to :cart_item
  
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_methods: { credit_card: 0, transfer: 1 }
 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :item
  belongs_to :order
end

app/models/orderdetail.rb
class Orderdetail < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :item
  belongs_to :order
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    #@orders = orders.customer
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  
  
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to  admin_item_path
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
   private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active)
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
  end
  
  private

  def order_params
    params.require(:order).permit(:address, :gip_code, :address_name, :payment_methods, :invoice_amount, :postage, :order_status)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:telephone_number])
    
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/item_helper.rb
module Admin::ItemHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CakeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <script src="https://kit.fontawesome.com/06d5403368.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"></a>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
    
        
          
            <% if  customer_signed_in? %>
              <li class="nav-item">
                <%= link_to "マイページ",  customers_mypage_path, class: 'nav-link' %>
              </li>
              
              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: 'nav-link' %>
              </li>
              
              <li class="nav-item">
                <%= link_to "カート", cart_items_path,  class: 'nav-link' %>
              </li>
              
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link' %>
              </li>
              
            <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "商品一覧",  admin_items_path, class: 'nav-link' %>
              </li>
              
              <li class="nav-item">
                <%= link_to "会員一覧", admin_customers_path, class: 'nav-link' %>
              </li>
              
              <li class="nav-item">
                <%= link_to "注文履歴一覧", admin_root_path,  class: 'nav-link' %>
              </li>
              
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "About", about_path, class: 'nav-link' %>
              </li>
                
              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: 'nav-link' %>
              </li>
                
              <li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link' %>
              </li>
              
              <li class="nav-item">
                <%= link_to "ログイン", new_customer_session_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
</header>
    
    
    <%= yield %>
    
    
  </body>
</html>